"""Deterministic markdown rendering for offline documentation mode."""

from __future__ import annotations

import tomllib
from dataclasses import dataclass
from pathlib import Path

from repo_autodocs.localization import GeneratedTextLanguage, localize
from repo_autodocs.models import (
    CodeFactsBundle,
    GroundedContextBundle,
    RepoManifest,
    RoutedAlignmentBundle,
    TheorySource,
)
from repo_autodocs.theory import ReferenceDiscovery

DOCFORGE_MANAGED_MARKER = "DOCFORGE:MANAGED"
PLACEHOLDER_MARKER = "AUTO-GENERATED PLACEHOLDER"


@dataclass(frozen=True, slots=True)
class DeterministicContext:
    manifest: RepoManifest
    theory_sources: list[TheorySource]
    code_facts_bundle: CodeFactsBundle
    grounded_bundle: GroundedContextBundle
    routed_alignment: RoutedAlignmentBundle | None = None


@dataclass(frozen=True, slots=True)
class ProjectMetadata:
    name: str | None
    description: str | None
    requires_python: str | None


def load_project_metadata(project_root: Path) -> ProjectMetadata:
    pyproject = project_root / "pyproject.toml"
    if not pyproject.exists():
        return ProjectMetadata(name=None, description=None, requires_python=None)

    try:
        data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
    except (tomllib.TOMLDecodeError, OSError):
        return ProjectMetadata(name=None, description=None, requires_python=None)

    project = data.get("project") if isinstance(data, dict) else None
    if not isinstance(project, dict):
        return ProjectMetadata(name=None, description=None, requires_python=None)

    def _v(key: str) -> str | None:
        value = project.get(key)
        return value if isinstance(value, str) else None

    return ProjectMetadata(
        name=_v("name"),
        description=_v("description"),
        requires_python=_v("requires-python"),
    )


def _top_modules(bundle: CodeFactsBundle, limit: int = 6) -> list[tuple[str, int, int]]:
    ranked = sorted(
        bundle.modules,
        key=lambda module: (
            module.defined_class_count + module.defined_function_count,
            module.import_count,
            module.module_name,
        ),
        reverse=True,
    )[:limit]
    return [
        (
            module.module_name,
            module.defined_class_count + module.defined_function_count,
            module.import_count,
        )
        for module in ranked
    ]


def _representative_symbols(bundle: CodeFactsBundle, limit: int = 10) -> list[str]:
    ranked = sorted(
        bundle.symbols, key=lambda item: (item.module_name, item.lineno, item.symbol_name)
    )
    return [
        f"`{symbol.module_name}.{symbol.symbol_name}` ({symbol.symbol_type})"
        for symbol in ranked[:limit]
    ]


def _entrypoints(bundle: CodeFactsBundle) -> list[str]:
    return bundle.detected_entrypoints[:10]


def _managed_header(page_label: str) -> str:
    return f"<!-- {DOCFORGE_MANAGED_MARKER} page={page_label} mode=deterministic -->"


def should_overwrite_managed_page(existing_text: str | None) -> bool:
    if not existing_text:
        return True
    return DOCFORGE_MANAGED_MARKER in existing_text or PLACEHOLDER_MARKER in existing_text


def render_home_page(
    project_root: Path, ctx: DeterministicContext, generated_text_language: GeneratedTextLanguage
) -> str:
    metadata = load_project_metadata(project_root)
    label = metadata.name or ctx.manifest.project_root.name
    top_modules = _top_modules(ctx.code_facts_bundle, limit=5)

    lines = [
        _managed_header("home"),
        "",
        f"# {label} Documentation",
        "",
        localize(
            generated_text_language,
            "home.generated_with_mode",
            "This site was generated by **DocForge Local** in **deterministic mode** (no LLM).",
        ),
        "",
        "## Observed project summary",
        "",
    ]

    if metadata.description:
        lines.append(f"- **pyproject description:** {metadata.description}")
    if not metadata.description:
        lines.append(
            localize(
                generated_text_language,
                "home.observed_summary_fallback",
                "- No concise project description was detected in `pyproject.toml` metadata.",
            )
        )

    lines.extend(
        [
            f"- **Top-level directories:** {len(ctx.manifest.top_level_directories)}",
            f"- **Top-level files:** {len(ctx.manifest.top_level_files)}",
            f"- **Python modules under `src/`:** {len(ctx.code_facts_bundle.modules)}",
            "- **Detected runtime entrypoints:** "
            f"{len(ctx.code_facts_bundle.detected_entrypoints)}",
            "",
            "## Orientation",
            "",
            "- [Project Brief](context/project_brief.md)",
            "- [Project Snapshot](generated/project_snapshot.md)",
            "- [Overview](generated/overview.md)",
            "- [Architecture](generated/architecture.md)",
            "- [Code Structure](generated/code_structure.md)",
            "- [Runtime Entrypoints](generated/runtime_entrypoints.md)",
            "- [Reference Alignment](generated/reference_alignment.md)",
            "- [Agent Instruction Alignment](generated/agent_instruction_alignment.md)",
            "- [README Claim Alignment](generated/readme_claim_alignment.md)",
            "- [Theory Alignment (Deprecated Compatibility)](generated/theory_alignment.md)",
            "",
            "## Key structural signals",
            "",
        ]
    )

    if top_modules:
        for module_name, symbol_count, import_count in top_modules:
            lines.append(f"- `{module_name}` (symbols={symbol_count}, imports={import_count})")
    else:
        lines.append(
            localize(
                generated_text_language,
                "home.key_structural_fallback",
                "- No Python module structure was detected under `src/`.",
            )
        )

    return "\n".join(lines).rstrip() + "\n"


def render_project_brief_page(
    project_root: Path, ctx: DeterministicContext, generated_text_language: GeneratedTextLanguage
) -> str:
    metadata = load_project_metadata(project_root)
    entrypoints = _entrypoints(ctx.code_facts_bundle)
    symbols = _representative_symbols(ctx.code_facts_bundle, limit=8)

    lines = [
        _managed_header("project_brief"),
        "",
        "# Project Brief",
        "",
        "## Observed evidence",
        "",
        f"- **Repository label:** `{ctx.manifest.project_root.name}`",
        f"- **pyproject name:** `{metadata.name}`"
        if metadata.name
        else "- **pyproject name:** not detected",
        f"- **pyproject requires-python:** `{metadata.requires_python}`"
        if metadata.requires_python
        else "- **pyproject requires-python:** not detected",
        f"- **Top-level directories:** {', '.join(ctx.manifest.top_level_directories) or 'none'}",
        f"- **Top-level files:** {', '.join(ctx.manifest.top_level_files[:12]) or 'none'}",
        f"- **Code modules discovered:** {len(ctx.code_facts_bundle.modules)}",
        f"- **Symbols discovered:** {len(ctx.code_facts_bundle.symbols)}",
        "",
        "## Cautious interpretation",
        "",
    ]

    if metadata.description:
        lines.append(f"- The package metadata describes the project as: {metadata.description}")
    if entrypoints:
        lines.append(
            "- Runtime entrypoints indicate executable surfaces: "
            + ", ".join(f"`{entry}`" for entry in entrypoints[:5])
        )
    if not metadata.description and not entrypoints:
        lines.append(
            localize(
                generated_text_language,
                "project_brief.interpretation_limited",
                "- Available deterministic evidence is limited; "
                "purpose cannot be confidently inferred.",
            )
        )

    lines.extend(["", "## Known uncertainty", ""])
    lines.append(
        localize(
            generated_text_language,
            "project_brief.known_uncertainty",
            "- This brief is generated only from deterministic repository/code evidence; "
            "it does not infer unstated product intent or deployment architecture.",
        )
    )
    if not ctx.theory_sources:
        lines.append(
            localize(
                generated_text_language,
                "project_brief.no_theory_sources",
                "- No external reference source files were discovered for additional grounding.",
            )
        )
    if symbols:
        lines.extend(["", "## Representative symbols", ""])
        lines.extend(f"- {symbol}" for symbol in symbols)

    return "\n".join(lines).rstrip() + "\n"


def render_external_references_page(
    *,
    discovery: ReferenceDiscovery,
    grounded_bundle: GroundedContextBundle,
    routed_alignment: RoutedAlignmentBundle | None,
    supported_ingest_extensions: list[str],
    generated_text_language: GeneratedTextLanguage,
) -> str:
    lines = [
        _managed_header("external_references"),
        "",
        "# External References",
        "",
        localize(
            generated_text_language,
            "external_refs.status_intro",
            "Status report for optional external reference materials.",
        ),
        "",
    ]
    explicit_sources = [source for source in discovery.sources if source.origin == "explicit"]
    default_sources = [source for source in discovery.sources if source.origin == "default"]
    if not discovery.sources:
        lines.extend(
            [
                localize(
                    generated_text_language,
                    "external_refs.none_supplied",
                    "No external reference materials were supplied for this run.",
                ),
                "",
                localize(
                    generated_text_language,
                    "external_refs.none_analysis",
                    "No additional reference analysis was performed.",
                ),
                "",
                localize(
                    generated_text_language,
                    "external_refs.enable_hint",
                    "To enable this feature, provide one of:",
                ),
                "- CLI: `--reference-path /path/to/references` (repeatable)",
                "- Env: `REPO_AUTODOCS_REFERENCE_PATHS=<path1><path_sep><path2>` "
                "(use your platform path separator, e.g., `:` on Unix-like shells "
                "and `;` on Windows)",
                '- Config: `[references].paths = ["/path/to/references"]`',
            ]
        )
        return "\n".join(lines).rstrip() + "\n"

    lines.extend(["## Discovery summary", ""])
    lines.append(f"- Explicit reference inputs discovered: {len(explicit_sources)}")
    lines.append(f"- Default-selected targets discovered: {len(default_sources)}")
    lines.append(f"- Total discovered files: {len(discovery.sources)}")
    lines.append(f"- Ingest-eligible files: {len(discovery.ingest_eligible_materials)}")
    lines.append(f"- Parsed files: {len(grounded_bundle.documents)}")
    unparsed_count = len(
        [source for source in discovery.sources if source.parse_status == "ingestible_unparsed"]
    )
    lines.append(f"- Not parsed files: {unparsed_count}")
    if routed_alignment is not None:
        lines.append(
            "- Routed alignment verdict totals: "
            f"reference={len(routed_alignment.reference_alignment.verdicts)}, "
            f"agent={len(routed_alignment.agent_instruction_alignment.verdicts)}, "
            f"readme={len(routed_alignment.readme_claim_alignment.verdicts)}"
        )
    lines.append(
        "- Ingestible file types in this release: "
        + ", ".join(f"`{ext}`" for ext in supported_ingest_extensions)
    )

    lines.extend(["", "## Inventory", ""])
    if discovery.sources:
        lines.append(
            "| Path | Origin | Kind | Route | Extension | Size (bytes) | Parse status | "
            "Grounding contribution | Route analysis | Why selected |"
        )
        lines.append("| --- | --- | --- | --- | --- | ---: | --- | --- | --- | --- |")
        for source in discovery.sources:
            ext = source.extension or "(none)"
            contribution = "yes" if source.participated_in_grounding else "no"
            route_status = _render_route_source_status(
                source.display_path, source.route, routed_alignment
            )
            lines.append(
                f"| `{source.display_path}` | `{source.origin}` | `{source.kind}` | "
                f"`{source.route}` | `{ext}` | {source.size_bytes} | `{source.parse_status}` | "
                f"{contribution} | {route_status} | {source.selection_reason} |"
            )
    else:
        lines.append(
            localize(
                generated_text_language,
                "external_refs.no_discovered_files",
                "No files were discovered for the selected reference inputs.",
            )
        )

    return "\n".join(lines).rstrip() + "\n"


def render_deterministic_sections(
    ctx: DeterministicContext, generated_text_language: GeneratedTextLanguage
) -> dict[str, str]:
    top_modules = _top_modules(ctx.code_facts_bundle, limit=8)
    entrypoints = _entrypoints(ctx.code_facts_bundle)

    overview = [
        "# Overview",
        "",
        "## What This Project Appears To Be",
        "",
        localize(
            generated_text_language,
            "overview.deterministic_notice",
            "This overview is deterministic and based on scanned repository/code evidence only.",
        ),
        "",
        "## Deterministic Observations",
        "",
        f"- Top-level directories: {', '.join(ctx.manifest.top_level_directories) or 'none'}",
        f"- Top-level files: {', '.join(ctx.manifest.top_level_files) or 'none'}",
        f"- Python modules: {len(ctx.code_facts_bundle.modules)}",
        f"- Detected entrypoints: {len(ctx.code_facts_bundle.detected_entrypoints)}",
        "",
        "## Major Structural Signals",
        "",
    ]
    if top_modules:
        overview.extend(
            f"- `{module_name}` (symbols={symbol_count}, imports={import_count})"
            for module_name, symbol_count, import_count in top_modules[:5]
        )
    else:
        overview.append(
            localize(
                generated_text_language,
                "overview.no_ranked_modules",
                "- No ranked Python modules were detected.",
            )
        )
    overview.extend(
        [
            "",
            "## Known Uncertainty",
            "",
            localize(
                generated_text_language,
                "overview.no_llm_uncertainty",
                "- No LLM synthesis was used in this run.",
            ),
        ]
    )

    architecture = [
        "# Architecture",
        "",
        "## Structural Organization",
        "",
        f"- `src/` present: `{ctx.manifest.has_src_dir}`",
        f"- `tests/` present: `{ctx.manifest.has_tests_dir}`",
        f"- `docs/` present: `{ctx.manifest.has_docs_dir}`",
        "",
        "## Components and Responsibility Hints",
        "",
    ]
    if top_modules:
        architecture.extend(
            "- "
            f"`{name}` likely contains meaningful logic volume "
            f"(symbols={symbols}, imports={imports})."
            for name, symbols, imports in top_modules
        )
    else:
        architecture.append(
            localize(
                generated_text_language,
                "architecture.no_boundaries",
                "- Deterministic component boundaries could not be derived from Python modules.",
            )
        )

    architecture.extend(["", "## Integration Signals", ""])
    if ctx.code_facts_bundle.imports:
        for edge in ctx.code_facts_bundle.imports[:10]:
            qualifier = "relative" if edge.relative else "absolute"
            architecture.append(
                f"- `{edge.source_module}` imports `{edge.imported_module}` ({qualifier})"
            )
    else:
        architecture.append(
            localize(
                generated_text_language,
                "architecture.no_import_edges",
                "- No import edges were extracted.",
            )
        )

    code_structure = [
        "# Code Structure",
        "",
        localize(
            generated_text_language,
            "code_structure.inventory_intro",
            "Deterministic inventory of Python modules and representative symbols.",
        ),
        "",
        "## Top modules",
        "",
    ]
    if top_modules:
        code_structure.extend(
            f"- `{name}` (symbols={symbols}, imports={imports})"
            for name, symbols, imports in top_modules
        )
    else:
        code_structure.append(
            localize(
                generated_text_language,
                "code_structure.no_modules",
                "- No Python modules detected under `src/`.",
            )
        )
    code_structure.extend(["", "## Representative symbols", ""])
    reps = _representative_symbols(ctx.code_facts_bundle, limit=15)
    if reps:
        code_structure.extend(f"- {symbol}" for symbol in reps)
    else:
        code_structure.append(
            localize(
                generated_text_language,
                "code_structure.no_symbols",
                "- No top-level classes/functions detected.",
            )
        )

    runtime_entrypoints = [
        "# Runtime Entrypoints",
        "",
        localize(
            generated_text_language,
            "runtime_entrypoints.page_intro",
            "This page lists deterministic runtime/CLI surfaces discovered from code facts.",
        ),
        "",
        "## Detected entrypoints",
        "",
    ]
    if entrypoints:
        runtime_entrypoints.extend(f"- `{entry}`" for entry in entrypoints)
    else:
        runtime_entrypoints.append(
            localize(
                generated_text_language,
                "runtime_entrypoints.none_detected",
                "- No explicit entrypoints were detected (`__main__`/Typer patterns).",
            )
        )

    runtime_entrypoints.extend(["", "## Notes", ""])
    runtime_entrypoints.append(
        localize(
            generated_text_language,
            "runtime_entrypoints.notes",
            "- Entrypoints are pattern-based detections and may not represent all runtime paths.",
        )
    )

    routed = ctx.routed_alignment or RoutedAlignmentBundle()

    reference_alignment = [
        "# Reference Alignment",
        "",
        localize(
            generated_text_language,
            "reference_alignment.page_intro",
            "Deterministic verdicts for general external reference materials.",
        ),
        "",
    ]
    _append_route_summary(
        reference_alignment,
        routed.reference_alignment,
        empty_label=localize(
            generated_text_language,
            "route_summary.empty_general",
            "- No general references discovered.",
        ),
    )

    agent_alignment = [
        "# Agent Instruction Alignment",
        "",
        localize(
            generated_text_language,
            "agent_alignment.page_intro",
            "Deterministic verdicts for AI-agent instruction files.",
        ),
        "",
    ]
    _append_route_summary(
        agent_alignment,
        routed.agent_instruction_alignment,
        empty_label=localize(
            generated_text_language,
            "route_summary.empty_agent",
            "- No agent instruction sources discovered.",
        ),
    )

    readme_alignment = [
        "# README Claim Alignment",
        "",
        localize(
            generated_text_language,
            "readme_alignment.page_intro",
            "Deterministic verdicts for README claims.",
        ),
        "",
    ]
    _append_route_summary(
        readme_alignment,
        routed.readme_claim_alignment,
        empty_label=localize(
            generated_text_language,
            "route_summary.empty_readme",
            "- No README sources discovered.",
        ),
    )

    theory_alignment = [
        "# Theory Alignment",
        "",
        "> Deprecated compatibility page: alignment now lives in dedicated routed pages.",
        "",
        "- [Reference Alignment](reference_alignment.md)",
        "- [Agent Instruction Alignment](agent_instruction_alignment.md)",
        "- [README Claim Alignment](readme_claim_alignment.md)",
        "",
    ]

    return {
        "overview.md": "\n".join(overview).rstrip() + "\n",
        "architecture.md": "\n".join(architecture).rstrip() + "\n",
        "reference_alignment.md": "\n".join(reference_alignment).rstrip() + "\n",
        "agent_instruction_alignment.md": "\n".join(agent_alignment).rstrip() + "\n",
        "readme_claim_alignment.md": "\n".join(readme_alignment).rstrip() + "\n",
        "theory_alignment.md": "\n".join(theory_alignment).rstrip() + "\n",
        "code_structure.md": "\n".join(code_structure).rstrip() + "\n",
        "runtime_entrypoints.md": "\n".join(runtime_entrypoints).rstrip() + "\n",
    }


def _append_route_summary(lines: list[str], result, *, empty_label: str) -> None:
    lines.extend(
        [
            "## Route summary",
            "",
            f"- Sources considered: {result.source_count}",
            f"- Extracted candidates: {len(result.candidates)}",
            f"- Verdicted items: {len(result.verdicts)}",
        ]
    )
    if result.verdict_counts:
        lines.append(
            "- Verdict counts: "
            + ", ".join(
                f"{status}={count}" for status, count in sorted(result.verdict_counts.items())
            )
        )
    lines.extend(["", "## Verdict examples", ""])
    if not result.verdicts:
        lines.append(empty_label)
        return
    for verdict in result.verdicts[:10]:
        lines.append(
            f"- `{verdict.verdict}` | `{verdict.source_path}` | {verdict.claim_text} "
            f"(evidence: {verdict.evidence_note})"
        )


def _route_result_for_source(route: str, routed_alignment: RoutedAlignmentBundle | None):
    if routed_alignment is None:
        return None
    if route == "general_reference_alignment":
        return routed_alignment.reference_alignment
    if route == "agent_instruction_alignment":
        return routed_alignment.agent_instruction_alignment
    if route == "readme_claim_alignment":
        return routed_alignment.readme_claim_alignment
    return None


def _render_route_source_status(
    source_path: str, route: str, routed_alignment: RoutedAlignmentBundle | None
) -> str:
    route_result = _route_result_for_source(route, routed_alignment)
    if route_result is None:
        return "attempted=no"
    related = [
        v
        for v in route_result.verdicts
        if v.source_path == source_path or v.source_path.startswith(f"{source_path}#")
    ]
    attempted = "yes" if related else "no"
    if not related:
        return f"attempted={attempted}; candidates=0; verdicts=0"
    counts: dict[str, int] = {}
    for verdict in related:
        counts[verdict.verdict] = counts.get(verdict.verdict, 0) + 1
    counts_text = ", ".join(f"{k}={v}" for k, v in sorted(counts.items()))
    return f"attempted={attempted}; candidates={len(related)}; {counts_text}"
